# 以相機座標系統到無人機座標系統的轉換，單位是公尺及度
# 以無人機為原點, 但以像素座標系統為基準, x軸向右, y軸向後, z軸向上
camera_offset:
  x: 0.0
  y: 0.125
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 180.0
camera_parameter:
  # 相機內部參數
  camera_matrix: 
    - [479.23864074, 0.0, 322.41904053]
    - [0.0, 478.87010769, 208.59056289]
    - [0.0, 0.0, 1.0]
  # 畸變係數
  distortion_coefficients: [-0.04673894, 0.12198613, 0.00533764, 0.00095581, -0.15779023]